### ISSUE TITLE
Change tests to inspec from serverspec

### ISSUE THREAD

**Issue by joshuacherry** [benwebber/ansible-minecraft#13]
I would like to migrate our tests over to inspec, most of it should be extremely easy to port over. Inspec seems to be significantly more active in development than serverspec.  

|            | Date Range                  | Pulse      | Overview     |
| :--------- | :----------------------:    | :--------: | :----------- |
| inspec     | April 9, 2017 – May 9, 2017 | [Pulse](https://github.com/chef/inspec/pulse/monthly) | Excluding merges, 20 authors have pushed 85 commits to master and 91 commits to all branches. On master, 139 files have changed and there have been 5,579 additions and 2,685 deletions. |
| serverspec | April 9, 2017 – May 9, 2017 | [Pulse](https://github.com/mizzy/serverspec/pulse/monthly) | There hasn’t been any commit activity on mizzy/serverspec in the last month. |

**Comment by benwebber** [comment]
This is the first I've heard of Inspec. While my personal preference is [testinfra](https://testinfra.readthedocs.org/), it's nice that the test suite is basically portable to Inspec.

Inspec also offers an [ini](https://www.inspec.io/docs/reference/resources/ini/) resource with which we might be able to test `server.properties`.
